/* original input */
/*
// create an array with nodes
var nodes = new vis.DataSet([
  { id: 1, label: "f", shape: "circle", color: "green" },
  { id: 2, label: "c", shape: "circle", color: "green" },
  { id: 3, label: "l", shape: "circle", color: "green" },
  { id: 4, label: "r", shape: "circle", color: "green" },
  { id: 5, label: "o", shape: "circle", color: "green" },
  { id: 6, label: "H", shape: "circle", color: "red" },
  { id: 7, label: "q", shape: "circle", color: "green" },
  { id: 8, label: "K", shape: "circle", color: "red" },
  { id: 9, label: "N", shape: "circle", color: "red" },
  { id: 10, label: "S", shape: "circle", color: "red" },
  { id: 11, label: "n", shape: "circle", color: "green" },
  { id: 12, label: "s", shape: "circle", color: "green" },
  { id: 13, label: "v", shape: "circle", color: "green" },
  { id: 14, label: "M", shape: "circle", color: "red" },
  { id: 15, label: "E", shape: "circle", color: "red" },
  { id: 16, label: "w", shape: "circle", color: "green" },
  { id: 17, label: "Z", shape: "circle", color: "red" },
  { id: 18, label: "J", shape: "circle", color: "red" },
  { id: 19, label: "a", shape: "circle", color: "green" },
  { id: 20, label: "X", shape: "circle", color: "red" },
  { id: 21, label: "D", shape: "circle", color: "red" },
  { id: 22, label: "I", shape: "circle", color: "red" },
  { id: 23, label: "A", shape: "circle", color: "red" },
  { id: 24, label: "t", shape: "circle", color: "green" },
  { id: 25, label: "b", shape: "circle", color: "green" },
  { id: 26, label: "i", shape: "circle", color: "green" },
  { id: 27, label: "G", shape: "circle", color: "red" },
  { id: 28, label: "e", shape: "circle", color: "green" },
  { id: 29, label: "T", shape: "circle", color: "red" },
  { id: 30, label: "y", shape: "circle", color: "green" },
  { id: 31, label: "@", shape: "circle", color: "black" },
  { id: 32, label: "U", shape: "circle", color: "red" },
  { id: 33, label: "u", shape: "circle", color: "green" },
  { id: 34, label: "B", shape: "circle", color: "red" },
  { id: 35, label: "x", shape: "circle", color: "green" },
  { id: 36, label: "z", shape: "circle", color: "green" },
  { id: 37, label: "V", shape: "circle", color: "red" },
  { id: 38, label: "d", shape: "circle", color: "green" },
  { id: 39, label: "j", shape: "circle", color: "green" },
  { id: 40, label: "g", shape: "circle", color: "green" },
  { id: 41, label: "Q", shape: "circle", color: "red" },
  { id: 42, label: "L", shape: "circle", color: "red" },
  { id: 43, label: "P", shape: "circle", color: "red" },
  { id: 44, label: "Y", shape: "circle", color: "red" },
  { id: 45, label: "k", shape: "circle", color: "green" },
  { id: 46, label: "O", shape: "circle", color: "red" },
  { id: 47, label: "p", shape: "circle", color: "green" },
  { id: 48, label: "F", shape: "circle", color: "red" },
  { id: 49, label: "W", shape: "circle", color: "red" },
  { id: 50, label: "m", shape: "circle", color: "green" },
  { id: 51, label: "h", shape: "circle", color: "green" },
  { id: 52, label: "R", shape: "circle", color: "red" },
  { id: 53, label: "C", shape: "circle", color: "red" },
]);
// create an array with edges
var edges = new vis.DataSet([
  { from: 1, to: 2 },
  { from: 1, to: 6 },
  { from: 1, to: 12 },
  { from: 1, to: 18 },
  { from: 1, to: 25 },
  { from: 1, to: 31 },
  { from: 1, to: 32 },
  { from: 1, to: 33 },
  { from: 1, to: 34 },
  { from: 1, to: 39 },
  { from: 1, to: 48 },
  { from: 1, to: 49 },
  { from: 2, to: 6 },
  { from: 2, to: 18 },
  { from: 2, to: 25 },
  { from: 2, to: 31 },
  { from: 2, to: 32 },
  { from: 2, to: 33 },
  { from: 2, to: 34 },
  { from: 2, to: 39 },
  { from: 2, to: 48 },
  { from: 2, to: 49 },
  { from: 3, to: 4 },
  { from: 3, to: 5 },
  { from: 4, to: 5 },
  { from: 4, to: 14 },
  { from: 5, to: 6 },
  { from: 6, to: 18 },
  { from: 6, to: 25 },
  { from: 6, to: 31 },
  { from: 6, to: 32 },
  { from: 6, to: 33 },
  { from: 6, to: 34 },
  { from: 6, to: 39 },
  { from: 6, to: 48 },
  { from: 6, to: 49 },
  { from: 7, to: 11 },
  { from: 7, to: 12 },
  { from: 8, to: 9 },
  { from: 8, to: 13 },
  { from: 9, to: 10 },
  { from: 9, to: 13 },
  { from: 10, to: 14 },
  { from: 11, to: 12 },
  { from: 11, to: 27 },
  { from: 13, to: 17 },
  { from: 15, to: 19 },
  { from: 15, to: 23 },
  { from: 16, to: 25 },
  { from: 17, to: 20 },
  { from: 18, to: 25 },
  { from: 18, to: 31 },
  { from: 18, to: 32 },
  { from: 18, to: 33 },
  { from: 18, to: 34 },
  { from: 18, to: 39 },
  { from: 18, to: 48 },
  { from: 18, to: 49 },
  { from: 19, to: 22 },
  { from: 19, to: 23 },
  { from: 19, to: 28 },
  { from: 20, to: 21 },
  { from: 21, to: 30 },
  { from: 22, to: 26 },
  { from: 22, to: 28 },
  { from: 24, to: 29 },
  { from: 24, to: 30 },
  { from: 25, to: 31 },
  { from: 25, to: 32 },
  { from: 25, to: 33 },
  { from: 25, to: 34 },
  { from: 25, to: 39 },
  { from: 25, to: 48 },
  { from: 25, to: 49 },
  { from: 26, to: 29 },
  { from: 29, to: 30 },
  { from: 31, to: 32 },
  { from: 31, to: 33 },
  { from: 31, to: 34 },
  { from: 31, to: 39 },
  { from: 31, to: 48 },
  { from: 31, to: 49 },
  { from: 32, to: 33 },
  { from: 32, to: 34 },
  { from: 32, to: 39 },
  { from: 32, to: 42 },
  { from: 32, to: 43 },
  { from: 32, to: 48 },
  { from: 32, to: 49 },
  { from: 32, to: 52 },
  { from: 33, to: 34 },
  { from: 33, to: 39 },
  { from: 33, to: 46 },
  { from: 33, to: 48 },
  { from: 33, to: 49 },
  { from: 34, to: 39 },
  { from: 34, to: 48 },
  { from: 34, to: 49 },
  { from: 35, to: 36 },
  { from: 35, to: 38 },
  { from: 36, to: 37 },
  { from: 37, to: 45 },
  { from: 38, to: 44 },
  { from: 39, to: 48 },
  { from: 39, to: 49 },
  { from: 40, to: 41 },
  { from: 41, to: 46 },
  { from: 41, to: 47 },
  { from: 41, to: 53 },
  { from: 42, to: 43 },
  { from: 42, to: 52 },
  { from: 43, to: 45 },
  { from: 43, to: 52 },
  { from: 46, to: 47 },
  { from: 46, to: 53 },
  { from: 47, to: 53 },
  { from: 48, to: 49 },
  { from: 49, to: 51 },
  { from: 50, to: 52 },
]);
*/
/*
#################
#i.G..c...e..H.p#
########.########
#j.A..b...f..D.o#
########@########
#k.E..a...g..B.n#
########.########
#l.F..d...h..C.m#
#################
*/

// create an array with nodes
var nodes = new vis.DataSet([
  { id: 1, label: "i", shape: "circle", color: "green" },
  { id: 2, label: "G", shape: "circle", color: "red" },
  { id: 3, label: "c", shape: "circle", color: "green" },
  { id: 4, label: "e", shape: "circle", color: "green" },
  { id: 5, label: "H", shape: "circle", color: "red" },
  { id: 6, label: "p", shape: "circle", color: "green" },
  { id: 7, label: "j", shape: "circle", color: "green" },
  { id: 8, label: "A", shape: "circle", color: "red" },
  { id: 9, label: "b", shape: "circle", color: "green" },
  { id: 10, label: "f", shape: "circle", color: "green" },
  { id: 11, label: "D", shape: "circle", color: "red" },
  { id: 12, label: "o", shape: "circle", color: "green" },
  { id: 13, label: "@", shape: "circle", color: "black" },
  { id: 14, label: "k", shape: "circle", color: "green" },
  { id: 15, label: "E", shape: "circle", color: "red" },
  { id: 16, label: "a", shape: "circle", color: "green" },
  { id: 17, label: "g", shape: "circle", color: "green" },
  { id: 18, label: "B", shape: "circle", color: "red" },
  { id: 19, label: "n", shape: "circle", color: "green" },
  { id: 20, label: "l", shape: "circle", color: "green" },
  { id: 21, label: "F", shape: "circle", color: "red" },
  { id: 22, label: "d", shape: "circle", color: "green" },
  { id: 23, label: "h", shape: "circle", color: "green" },
  { id: 24, label: "C", shape: "circle", color: "red" },
  { id: 25, label: "m", shape: "circle", color: "green" },
]);
// create an array with edges
var edges = new vis.DataSet([
  { from: 1, to: 2, label: "2" },
  { from: 2, to: 3, label: "3" },
  { from: 3, to: 4, label: "4" },
  { from: 3, to: 9, label: "6" },
  { from: 3, to: 10, label: "6" },
  { from: 3, to: 13, label: "5" },
  { from: 4, to: 5, label: "3" },
  { from: 4, to: 9, label: "6" },
  { from: 4, to: 10, label: "6" },
  { from: 4, to: 13, label: "5" },
  { from: 5, to: 6, label: "2" },
  { from: 7, to: 8, label: "2" },
  { from: 8, to: 9, label: "3" },
  { from: 9, to: 10, label: "4" },
  { from: 9, to: 13, label: "3" },
  { from: 10, to: 11, label: "3" },
  { from: 10, to: 13, label: "3" },
  { from: 11, to: 12, label: "2" },
  { from: 13, to: 16, label: "3" },
  { from: 13, to: 17, label: "3" },
  { from: 13, to: 22, label: "5" },
  { from: 13, to: 23, label: "5" },
  { from: 14, to: 15, label: "2" },
  { from: 15, to: 16, label: "3" },
  { from: 16, to: 17, label: "4" },
  { from: 16, to: 22, label: "6" },
  { from: 16, to: 23, label: "6" },
  { from: 17, to: 18, label: "3" },
  { from: 17, to: 22, label: "6" },
  { from: 17, to: 23, label: "6" },
  { from: 18, to: 19, label: "2" },
  { from: 20, to: 21, label: "2" },
  { from: 21, to: 22, label: "3" },
  { from: 22, to: 23, label: "4" },
  { from: 23, to: 24, label: "3" },
  { from: 24, to: 25, label: "2" },
]);


// create a network
var container = document.getElementById("mynetwork");
var data = {
  nodes: nodes,
  edges: edges
};
var options = {
  nodes: {
    shape: "box",

    font : {
        size: 50
    }
  },

  edges: {
    font : {
        size: 40
    }
  }
};
var network = new vis.Network(container, data, options);

